version: '3.1'
services:
  db:
    image: postgres
    container_name: database_postgres
    environment: #this is not safe, for the sake of simplicity I leave like that
      POSTGRES_PASSWORD: password
      POSTGRES_USER: codemotion
      POSTGRES_DB: shopping_db

  adminer:
    image: adminer
    container_name: database_webgui
    depends_on:
      - db
    ports:
      - 8080:8080

#  backend:
#    build: backend/
#    container_name: flask_backend
#    depends_on:
#      - db
#    ports:
#    - 5000:5000