version: '3.1'
services:
  db:
    image: postgres
    container_name: database_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: codemotion
      POSTGRES_DB: shopping_db

  adminer:
    image: adminer
    container_name: database_webgui
    depends_on:
      - db
    ports:
    - 8080:8080