"""add product name

Revision ID: 8f0c2969080b
Revises: d29a2791fb67
Create Date: 2021-06-21 14:25:14.735294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0c2969080b'
down_revision = 'd29a2791fb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
