"""fix shopping list fk

Revision ID: d29a2791fb67
Revises: 7294f04c9190
Create Date: 2021-06-17 13:11:13.727863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29a2791fb67'
down_revision = '7294f04c9190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_lists', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_lists', type_='foreignkey')
    op.drop_column('shopping_lists', 'owner_id')
    # ### end Alembic commands ###
